[Design] Onboarding
DDD-Community/MorningBear pull request #107
Opened 2023-02-08 03:53 UTC by 2dubu

## What is this PR? 👀
온보딩 화면 디자인 적용
<br><br/>

## Changes 📃
이미지 추가 및 버튼 기능 추가
<br><br/>

## Screenshot (optional) 📷
![RPReplay_Final1675828276](https://user-images.githubusercontent.com/70322775/217428284-a30d13c2-7526-4f47-9ccf-adf4e75408f1.gif)
<br><br/>

## Additional & Warning points (optional) 📌
page control custom은 아직 진행하지 않음
<br><br/>

## Test result 🧪
직접 실행을 통해 테스트 완료

2023-02-08 09:22 UTC, enebin requested changes

2023-02-08 09:22 UTC, enebin commented on Targets/MorningBear/Sources/Onboarding/OnboardingViewModel.swift
>  import MorningBearData
이거 여기 있으면 안 됨.  ([참고](https://github.com/DDD-Community/MorningBear-iOS/wiki/%EB%AA%A8%EB%93%88-%EC%BB%A8%EB%B2%A4%EC%85%98#3-%ED%95%98%ED%96%A5%EA%B4%80%EA%B3%84%EB%A5%BC-%EB%9B%B0%EC%96%B4%EB%84%98%EC%96%B4-%EC%B0%B8%EC%A1%B0-%EA%B8%88%EC%A7%80))

2023-02-09 04:05 UTC, 2dubu commented on Targets/MorningBear/Sources/Onboarding/OnboardingViewModel.swift
>  import MorningBearData
@enebin 그럼 viewModel이 이미지를 정보를 가지고 있어야 할 때는 어떤 식으로 처리해주어야 하나용

2023-02-09 08:35 UTC, enebin commented on Targets/MorningBear/Sources/Onboarding/OnboardingViewModel.swift
>  import MorningBearData
주의사항 3번 참고하면 됨. 다른 cell이나 data model들 보면 나와있음.

2023-02-09 09:13 UTC, enebin commented
@2dubu 이거 내 시뮬레이터에서 화면이 안 뜨는데 원래 첫화면이 이래? 너도 그런지 한 번만 확인 부탁
<img width="346" alt="image" src="https://user-images.githubusercontent.com/46271447/217766407-4e7fb913-88cf-4961-95ef-ad3ec19b8663.png">

2023-02-09 09:25 UTC, 2dubu commented
> @2dubu 이거 내 시뮬레이터에서 화면이 안 뜨는데 원래 첫화면이 이래? 너도 그런지 한 번만 확인 부탁

저는 이상 없이 잘 떠요!

2023-02-09 09:27 UTC, enebin commented
> > @2dubu 이거 내 시뮬레이터에서 화면이 안 뜨는데 원래 첫화면이 이래? 너도 그런지 한 번만 확인 부탁
> 
> 저는 이상 없이 잘 떠요!

에러 로그 보니까 cell에서 이미지 높이 고정값으로 둬서 그러는 것 같은데 이미지 높이 고정값으로 두지 말고 aspect ratio같은 걸로 바꿔서 넣어야할 것 같음. 부등호로 넣어도 되고.

2023-02-11 11:00 UTC, enebin approved these changes

2023-02-11 11:04 UTC, merged

2023-02-11 11:04 UTC, enebin commented
엥 뭐야 큐에 올리니까 그냥 머지 돼버렸네

2023-02-11 11:07 UTC, enebin commented
쨋든 온보딩 리모트 브랜치는 지울테니까 develop 위에서 다시 작업하면 될 듯. 원래 쓰던 거 있으면 리베이스 하고.