[Refactor] Update design to the newest
DDD-Community/MorningBear pull request #77
Opened 2023-01-14 12:32 UTC by enebin

## What is this PR? 👀
- 피그마와 1차적으로 디자인 싱크
<br><br/>

## Changes 📃
- 전체적으로 보기 좋아짐
<br><br/>

## Screenshot (optional) 📷
![Simulator Screen Recording - iPhone 14 Pro - 2023-01-14 at 21 31 40](https://user-images.githubusercontent.com/46271447/212471674-2e6ea64c-c4d3-413e-92a9-4625c7a08ff7.gif)

<br><br/>

## Additional & Warning points (optional) 📌
- #74 해결
<br><br/>

## Test result 🧪
- 뷰 모델 일부 코드에 대해 테스트 코드 작성
- 빌드 확인

2023-01-14 15:31 UTC, 2dubu requested changes

2023-01-14 15:31 UTC, 2dubu commented on Targets/MorningBear/Sources/Home/Register morning/RegisterMorningViewController.swift
> +    @IBOutlet var topmostView: UIView!
`weak` 없어도 괜찮나요?

2023-01-14 15:31 UTC, 2dubu commented on Targets/MorningBear/Sources/Home/HomeViewController.swift
> +            recordingNowButton.layer.shadowRadius = 15
Figma 보니까 섀도우 스타일이 따로 지정되어 있는 것 같아서, UI 타겟쪽에 섀도우 스타일을 따로 enum으로 관리하면 어떨까요?


<img width="1135" alt="스크린샷 2023-01-15 오전 12 30 05" src="https://user-images.githubusercontent.com/70322775/212479783-6b14a24d-d897-4064-8fdd-812a06e6928e.png">

2023-01-15 03:19 UTC, enebin commented on Targets/MorningBear/Sources/Home/Register morning/RegisterMorningViewController.swift
> +    @IBOutlet var topmostView: UIView!
얘는 사용한 적이 없는 것 같아서 그냥 삭제함

2023-01-15 03:43 UTC, enebin commented on Targets/MorningBear/Sources/Home/HomeViewController.swift
> +            recordingNowButton.layer.shadowRadius = 15
나도 섀도우 스타일 걸려있는 걸 본 것 같은데 일단 스탠다드만 만들어서 올려놓음

2023-01-16 07:57 UTC, 2dubu approved these changes

2023-01-16 07:58 UTC, 2dubu commented on Targets/MorningBear/Sources/Home/HomeViewController.swift
> +            recordingNowButton.layer.shadowRadius = 15
👍

2023-01-16 10:03 UTC, merged