[Feature] Basic info view
DDD-Community/MorningBear pull request #94
Opened 2023-01-26 18:02 UTC by 2dubu

## What is this PR? 👀
네트워크를 제외한 로그인 후 기본정보 입력 화면 개발
<br><br/>

## Changes 📃
계속해서 뷰가 푸시되는 모양이 좋지 않아보여 pageViewController를 사용해서 개발
<br><br/>

## Screenshot (optional) 📷
![RPReplay_Final1674755437](https://user-images.githubusercontent.com/70322775/214912298-d0f1e50d-d8ab-4416-a2b9-478066eed894.gif)
<br><br/>

## Additional & Warning points (optional) 📌
1. ~~각각의 Input view들이 좌우로 scroll & bounce 되는 현상이 있음. (해결)~~
2. 앱에서 공통으로 사용될 Custom half modal이 정해지지 않아 해당 기능은 제외하고 개발 (기상 시간 입력 화면)
3. 네트워크 작업은 변경된 타겟 환경에서 진행할 예정

한번에 작업하려다 생각보다 손이 많이 가서 PR단위가 너무 커져버렸음.. 🥲
<br><br/>

## Test result 🧪
직접 실행하며 테스트 진행했습니다

2023-01-27 11:31 UTC, 2dubu commented
Todo : fix shared view model property

2023-01-28 04:40 UTC, enebin requested changes

2023-01-28 04:40 UTC, enebin commented on Targets/MorningBear/Sources/Login/InitialInfoViewModel.swift
> +    static let shared = InitialInfoViewModel()
♻️

2023-01-28 04:42 UTC, enebin commented on Targets/MorningBear/Sources/Login/InitialInfoViewModel.swift
> +    static let shared = InitialInfoViewModel()
1. `static`에서 일반 변수로 변경
2. 각 하위 view controller에서 shared로 접근하는게 아니라 InitialInfoViewController에서 만든 뷰모델 인스턴스를 직접 넘겨줬으면 좋겠음.

2023-02-07 01:09 UTC, enebin commented on Targets/MorningBear/Sources/Login/InitialInfoViewModel.swift
> +    var canGoNext: BehaviorRelay<[Bool]>
이거를 `bool`의 어레이로 관리하는 이유가 있었음?? 어레이 말고 그냥 변수로 관리해도 되지 않나 싶은데 내가 놓친 게 있나 싶어서

2023-02-07 01:09 UTC, enebin commented on Targets/MorningBear/Sources/Login/InitialInfoViewController.swift
> +                    owner.viewModel.canGoNext.accept(owner.viewModel.canGoNext.value)
(아래에서) 어레이 쓴 이유가 있냐고 물어본 이유는 이런 게 코드만 보고 의도를 바로 이해하기가 힘들어서.

2023-02-07 04:54 UTC, 2dubu commented on Targets/MorningBear/Sources/Login/InitialInfoViewModel.swift
> +    var canGoNext: BehaviorRelay<[Bool]>
@enebin 총 4페이지가 있는데 하나의 변수로 관리했을 때는 뒤로가기 버튼을 눌렀을 때 버튼의 상태를 기억(저장)하기가 힘들어서 배열로 변경해봤어용

2023-02-07 04:55 UTC, 2dubu commented on Targets/MorningBear/Sources/Login/InitialInfoViewController.swift
> +                    owner.viewModel.canGoNext.accept(owner.viewModel.canGoNext.value)
그리고 요건 `currentIndex`가 변경되었을 때 `canGoNext`에 노티를 주기위해서 같은 값을 한 번 더 주입해준 부분입니다

2023-02-07 10:13 UTC, enebin commented on Targets/MorningBear/Sources/Login/InitialInfoViewModel.swift
> +    var canGoNext: BehaviorRelay<[Bool]>
어레이 중 하나만 `true`인게 보장이 안 되지 않아? 에러 방지를 위해서 `true`인 값이 오직 하나만 존재하게 관리가 필요할 것 같은데 이 부분이 해결되면 좋을 듯. 내가 못 본거면 스킵하고,,

2023-02-07 10:13 UTC, enebin commented on Targets/MorningBear/Sources/Login/InitialInfoViewModel.swift
> +    var canGoNext: BehaviorRelay<[Bool]>
@2dubu

2023-02-07 10:26 UTC, enebin approved these changes

2023-02-07 10:34 UTC, merged